version: "3.9"
services:
  pg_db:
    container_name: pg_db
    image: postgres:14.7-alpine
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  comlink:
      image: ghcr.io/swgoh-utils/swgoh-comlink:latest
      container_name: swgoh-comlink
      restart: always
      environment:
        - APP_NAME=shtierlitz_comlinc
      ports:
        - 3000:3000
      networks:
        - app-network


  bot:
    build: .
    command: python bot_telegram.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      pg_db:
        condition: service_healthy
      comlink:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
